---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
    - name: Configuring SNMP
      ios_config:
        commands:
        - snmp-server community "{{ dafak }}" RO 20
        - snmp-server community "{{ hostname }}" RW 30
    
    - name: Check ACL
      ios_command:
        commands:
        - "{{ filter }}"
      register: showacl
    
    - debug: "msg='NO ACCESS LIST 30'"
      var: showacl.stdout_lines
      when: showacl.stdout_lines[0][0] == ''
