---
- hosts: switches
  connection: local
  vars:
    hostname: JPTYO
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Configuring SNMP
      ios_config:
        commands:
        - snmp-server community "{{ dafak }}" RO 20
        - snmp-server community "{{ hostname }}" RW 30
    
    - name: Check ACL
      ios_command:
        commands:
        - show run | inc access-list 10
      register: showacl
    
    - debug: "msg='access list 10'"
      when: '"access-list 10 permit 0.0.0.0 255.0.0.0\naccess-list 10 permit 0.0.0.0 255.255.0.0\naccess-list 10 permit 0.0.0.0 255.255.255.0" in showacl.stdout'

