---
- hosts: switches
  connection: local
  vars:
    hostname: JPTYO
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Configuring SNMP
      ios_config:
        commands:
        - snmp-server community test123 RO 20
        - snmp-server community test321 RW 30
        - snmp-server location "{{ hostname }}"
