---
- hosts: switches
  connection: local
  vars:
    hostname: JPTYO
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: CmdLine JSON - list
      debug:
        msg: "{{ hostname }}"
