---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
    - name: Configuring SNMP
      ios_config:
        commands:
        - snmp-server community {{snmp1}} RO 20
        - snmp-server community {{snmp2}} RW 30
        before:
        - no snmp-server community aris RO20
        - no snmp-server community perangin2 RW 30
        
    - name: Check ACL
      ios_command:
        commands:
        - show run | inc access-list 101
      register: showacl
    
    - debug:
        var: showacl.stdout_lines[0][0]
