---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
    - name: Configuring SNMP
      ios_config:
        commands:
        - snmp-server community {{snmp1}} RO 20
        - snmp-server community {{snmp2}} RW 30
