---
- hosts: all
  connection: local
  vars:
    hostname: JPTYO
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Configuring SNMP
      ios_config:
        commands:
        - snmp-server community "{{ dafak }}" RO 20
        - snmp-server community "{{ hostname }}" RW 30
    
    - name: Check ACL
      ios_command:
        commands:
        - show run | inc access-list 10
      register: showacl
    
    - debug: "msg='NO ACCESS LIST 10'"
      when: showacl.stdout_lines[0][0] == ''
