---
- hosts: switches
  connection: local
  vars:
    hostname: JPTYO
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: Configuring SNMP
      ios_config:
        commands:
        - snmp-server community "{{ dafak }}" RO 20
        - snmp-server community "{{ hostname }}" RW 30
    
    - name: Check ACL
      ios_command:
        commands:
        - show ip access-list
      register: showacl
    
    - debug: "msg='access list 10'"
      when: showacl.stdout | join(" ") | search("access list 10")  

