---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:  
    - name: Check ACL
      ios_command:
        commands:
        - show run | inc access-list 40
      register: showacl
    
    - debug: "msg='NO ACCESS LIST 30'"
      when: showacl.stdout_lines[0][0] == ''

