---
- hosts: all
  connection: local
  serial: 1
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: saving configuration
    aireos_command:
      commands:
        - command: save config
          prompt: "Are you sure you want to save? (y/n) "
          answer: y
    register: save_result
 
  - debug: 
      msg: " {{ save_result }} "
