---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - set_fact:
      temp: "{{ aplist[0] }}"

  - shell: "echo {{ item }}"
    with_items:
      {{aplist}}
    register: echo
