---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - set_fact:
      temp: "{{ aplist[0] }}"

  - debug: 
      msg: " {{temp}} "
    when: aplist[0] != ''
