---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: Check AP and Channel
    aireos_command:
      commands:
        - command: grep include "{{ item }}" "show advance 802.a summary"
          prompt: "Press any key to continue.."
          answer: y
    register: showap
    with_items:
       - "JPNFRT"
       - "AP"
    
      
  - debug: msg="{{ showap }}"
