---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: Check AP and Channel
    aireos_command:
      commands:
        - command: grep include {{items.name}} "show advance 802.a summary"
          prompt: "Press any key to continue.."
          answer: y
    with_items:
      {{aplist}}
    register: showap
  
  - set_fact:
      wlanid: "{{ showap.stdout_lines[0][1]}}"
      
  - debug: msg="{{ wlanid }}"
