---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
    - name: Define Timeout
      set_fact:
        provider:
          timeout: 60
    
    - name: Check ACL
      ios_command:
        provider: "{{ provider }}"
        commands:
        - "{{ filter }}"
      register: showacl
    
    - name: Extracting data
      set_fact:  
        showacl_mod: showacl.stdout
    
    - name: Searching ACL
      set_fact:
        show_acl: "{{ showacl_mod | join('\n') }}"
    
    - debug:
        var: show_acl.stdout
