---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
    - name: Define Timeout
      set_fact:
        provider:
          timeout: 60
    
    - name: Check ACL
      ios_command:
        provider: "{{ provider }}"
        commands:
        - "{{ filter }}"
      register: showacl
    
    - debug:
        "msg='no access list 123'"
      when: showacl.stdout | join(" ") | search("access list preauth_ipv4_acl")  
