---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
    - name: Define Timeout
      set_fact:
        provider:
          timeout: 60
    
    - name: Check ACL
      ios_command:
        provider: "{{ provider }}"
        commands:
        - "{{ filter }}"
      register: showacl
    
    - debug:
        var: showacl.stdout
