---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:  
    - name: Check ACL
      ios_command:
        commands:
        - "{{ filter }}"
      timeout: 50
      register: showacl
    
    - debug:
        "msg='access list 10'"
      when: '"access list 10" in showacl.stdout_lines'
