---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:  
    - name: Check ACL
      ios_command:
        commands:
        - "{{ filter }}"
        timeout: 300
      register: showacl
    
    - debug:
        var: showacl.stdout_lines
