---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:  
    - name: Check ACL
      ios_command:
        commands:
        - "{{ filter }}"
      register: showacl
    
    - debug: "msg='NO ACCESS LIST 40'"
      when: showacl.stdout_lines[0][0] == ''
