---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: Getting r-internet password
    aireos_command:
      commands:
        - show sysinfo
        - show interface summary
      wait_for:
        - result[0] contains Cisco Controller
        - result[1] contains Loopback0
