---
- hosts: all
  connection: local
  vars:
    cli:
      host: {{inven}}
      
  tasks:
  - name: configure configuration
    aireos_config:
      lines: sysname {{hostname}}

  - name: load new acl into device
    aireos_config:
      lines:
        - acl create testACL
        - acl rule protocol testACL 1 any
        - acl rule direction testACL 3 in
      before: acl delete testACL
