---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: Getting r-internet password
    aireos_command:
      commands: grep include r-internet "show wlan summary"
      wait_for: result[0]
  
  - name: Display Result In Loop
    debug: msg="WLAN-ID is {{ result.stdout[1] }}"
