---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: run show sysinfo and check to see if output contains Cisco Controller
    aireos_command:
      commands: grep include r-internet 'show wlan summary'
      prompt:"Press any key to continue\.\."
      response: k
    register: showacl

  - debug:
      var: showacl.stdout_lines
