---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: run show sysinfo and check to see if output contains Cisco Controller
    aireos_command:
      commands:
        - command: transfer download start
          prompt: "Press any key to continue.."
          response: y
    register: showacl

  - debug:
      var: showacl.stdout_lines
