---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: configure configuration
    aireos_config:
      lines: sysname {{hostname}}

  - name: load new acl into device
    aireos_config:
      lines:
        - acl create testACL
        - config acl rule add testACL 1
        - config acl rule destination port range testACL 1 22 22 
        - config acl rule source port range testACL 1 0 65535 
        - config acl rule protocol testACL 1 6 
      before: acl delete testACL
