---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: run show sysinfo and check to see if output contains Cisco Controller
    aireos_command:
      commands: 
      - show wlan summary
      wait_for: result[0] contains 'r-internet'
    register: showacl

  - debug:
      var: showacl.stdout
