---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: run show sysinfo and check to see if output contains Cisco Controller
    aireos_command:
      commands: show sysinfo
    register: showacl

  - debug:
      var: showacl_lines[0][1]
