---
- hosts: all
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      
  tasks:
  - name: Check WLAN-ID for r-internet
    aireos_command:
      commands:
        - command: grep include r-internet "show wlan summary"
          prompt: "Press any key to continue.."
          answer: y
    register: showacl
  
  - set_fact:
      temp: "{{ showacl.stdout_lines[0][1] }}"
  
  - set_fact:
      wlanid: "{{ temp.split() [0] }}"
      
  - debug: msg="{{ wlanid }}"
  
  - name: Change Password of r-internet
    aireos_config:
      lines:
        - wlan disable {{wlanid}}
        - wlan security wpa akm psk set-key ascii {{pwd}} {{wlanid}}
